# Site settings
title: Terence Tam
header-img: img/bg-sf.jpg
description: "Terence's Blog"
baseurl: ""
url: "http://terencekwt.github.io"
twitter_username: ilovepython
github_username: terencekwt
flickr_username: ilovepython
linkedin_url: http://linkedin.com/in/terencektam


# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
gems: [jekyll-paginate]
