# Site settings
title: Terence Tam
header-img: img/bg-sf.jpg
email: your-email@yourdomain.com
description: "Terence's Blog"
baseurl: ""
url: "http://terencekwt.github.io"
twitter_username:
github_username:
facebook_username:

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
